# Generated by Django 6.0.3 on 2026-04-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tapasapp", "0002_alter_dish_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
    ]
